name: Pytest + Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.10.0rc2'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: ‘2’
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.10.0-rc.2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry wheel
          poetry config experimental.new-installer false
          poetry install --no-root -E djantic
      - name: Test with pytest + generate coverage
        run:
          pytest -s -rf -vv --log-level=debug --cov-config=.coveragerc --cov cats tests
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
